---
- name: Install Jenkins Server
  hosts: jenkins
  become: yes

  tasks:

    - name: Update packages
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - openjdk-21-jdk
          - git
          - docker.io
          - curl
        state: present

    - name: Download Jenkins 2026 key
      shell: |
        curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2026.key -o /usr/share/keyrings/jenkins-keyring.asc

    - name: Add Jenkins repository
      copy:
        dest: /etc/apt/sources.list.d/jenkins.list
        content: |
          deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/

    - name: Update package cache after Jenkins repo
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Start and enable Jenkins
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Add Jenkins user to Docker group
      user:
        name: jenkins
        groups: docker
        append: yes
