---
- name: Install Jenkins Server
  hosts: jenkins
  become: yes

  tasks:

    - name: Update packages
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: openjdk-21-jdk
        state: present

    - name: Add Jenkins repository key
      shell: |
        wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | apt-key add -

    - name: Add Jenkins repository
      shell: |
        echo "deb https://pkg.jenkins.io/debian-stable binary/" > /etc/apt/sources.list.d/jenkins.list

    - name: Update package cache again
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start Jenkins
      service:
        name: jenkins
        state: started
        enabled: yes
